# Use the official Python image as a base image
FROM python:3.13-slim

# Set the working directory within the container
WORKDIR /app

# Copy the current directory contents into the container at /app
# COPY . /app
COPY requirements.txt /app/requirements.txt

RUN pip install -r requirements.txt